// web/src/components/ToolBar.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';

import Toolbar from 'primevue/toolbar';
import Button from 'primevue/button';
import Dropdown from 'primevue/dropdown';

import { examplePrograms } from '../lib/Examples';
import { Program } from 'logic-mesh';
import { useEngine } from '../lib/Engine';

const emit = defineEmits<{
	(event: 'reset'): void,
	(event: 'copy'): void
	(event: 'paste'): void
	(event: 'load', program: Program): void
}>()

const { command } = useEngine()

const isRunning = ref(true)
const curProgram = ref({} as Program)

onMounted(() => {
	curProgram.value = examplePrograms[1]
	//emit('load', curProgram.value)
})

function onPauseResume() {
	if (isRunning.value) {
		command.pauseExecution()
	} else {
		command.resumeExecution()
	}

	isRunning.value = !isRunning.value
}

function onReset() {
	isRunning.value = true
	emit('reset')
}

function onPaste() {
	if (!isRunning.value) {
		command.resumeExecution().then(() => {
			isRunning.value = true
			emit('paste')
		})
	} else {
		emit('paste')
	}
}

</script>

<template>
	<Toolbar>
		<template #start>
			<Dropdown v-model="curProgram" :options="examplePrograms" optionLabel="name" placeholder="Select a Program"
				@change="emit('load', curProgram)" class="w-full md:w-14rem" />
		</template>
		<template #center>
			<Button title="Pause/Resume execution" :icon="'pi ' + (isRunning ? 'pi-pause' : 'pi-play')" rounded
				@click="onPauseResume" />
		</template>
		<template #end>
			<div class="flex-grow">
				<Button title="Copy program" :icon="'pi pi-copy'" class="m-1" @click="emit('copy')" />
				<Button title="Paste program" :icon="'pi pi-file'" class="m-1" @click="onPaste" />
				<Button title="Reset engine" :icon="'pi pi-refresh'" rounded @click="onReset" class="m-1" />
			</div>
		</template>
	</Toolbar>
</template>

// web/app/src/components/ToolBar.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Play, Pause, Copy, ClipboardPaste, RotateCcw, FilePlus } from 'lucide-svelte';
	import { Button } from '$lib/components/ui/button';
	import {
		Select,
		SelectContent,
		SelectItem,
		SelectTrigger
	} from '$lib/components/ui/select';
	import { Separator } from '$lib/components/ui/separator';
	import { examplePrograms } from '$lib/Examples';
	import { useEngine } from '$lib/Engine';
	import type { Program } from 'logic-mesh';

	interface Props {
		onReset: () => void;
		onCopy: () => void;
		onPaste: () => void;
		onLoad: (program: Program) => void;
	}

	let { onReset, onCopy, onPaste, onLoad }: Props = $props();

	const { command } = useEngine();

	let isRunning = $state(true);
	let selectedIndex = $state<string>('1');

	const curProgram = $derived(examplePrograms[Number(selectedIndex)]);

	onMount(() => {
		onLoad(curProgram);
	});

	function onPauseResume() {
		if (isRunning) {
			command.pauseExecution();
		} else {
			command.resumeExecution();
		}
		isRunning = !isRunning;
	}

	function handleNew() {
		isRunning = true;
		selectedIndex = '';
		onReset();
	}

	function handleReset() {
		isRunning = true;
		onReset();
	}

	function handlePaste() {
		if (!isRunning) {
			command.resumeExecution().then(() => {
				isRunning = true;
				onPaste();
			});
		} else {
			onPaste();
		}
	}
</script>

<div class="flex min-w-[30em] items-center gap-2 rounded-lg border bg-background px-3 py-2 shadow-md">
	<!-- Program selector -->
	<Select
		type="single"
		value={selectedIndex}
		onValueChange={(v) => {
			selectedIndex = v;
			onLoad(examplePrograms[Number(v)]);
		}}
	>
		<SelectTrigger class="w-40">
			{curProgram?.name ?? 'Select a Program'}
		</SelectTrigger>
		<SelectContent>
			{#each examplePrograms as program, i}
				<SelectItem value={String(i)}>{program.name}</SelectItem>
			{/each}
		</SelectContent>
	</Select>

	<Separator orientation="vertical" class="h-6" />

	<!-- Play/Pause -->
	<Button variant="outline" size="icon" title="Pause/Resume execution" onclick={onPauseResume}>
		{#if isRunning}
			<Pause class="h-4 w-4" />
		{:else}
			<Play class="h-4 w-4" />
		{/if}
	</Button>

	<Separator orientation="vertical" class="h-6" />

	<!-- Actions -->
	<Button variant="outline" size="icon" title="New program" onclick={handleNew}>
		<FilePlus class="h-4 w-4" />
	</Button>
	<Button variant="outline" size="icon" title="Copy program" onclick={onCopy}>
		<Copy class="h-4 w-4" />
	</Button>
	<Button variant="outline" size="icon" title="Paste program" onclick={handlePaste}>
		<ClipboardPaste class="h-4 w-4" />
	</Button>
	<Button variant="outline" size="icon" title="Reset engine" onclick={handleReset}>
		<RotateCcw class="h-4 w-4" />
	</Button>
</div>
