// web/src/components/blocks/CheckboxBlock.svelte
<script lang="ts">
	import { Handle, Position } from '@xyflow/svelte';
	import { Checkbox } from '$lib/components/ui/checkbox';
	import BlockCommons from '../BlockCommons.svelte';
	import { useEngine } from '$lib/Engine';
	import type { Block } from '$lib/Block';

	interface Props {
		data: { value: Block };
	}

	let { data }: Props = $props();
	const { command } = useEngine();

	const block = $derived(data.value);
	const inputKey = $derived(Object.keys(block.inputs)[0] ?? 'in');
	const outputKey = $derived(Object.keys(block.outputs)[0] ?? 'out');

	function onCheckedChange(checked: boolean) {
		command.writeBlockOutput(block.id, outputKey, checked);
	}
</script>

<BlockCommons data={block}>
	<Handle id={inputKey} type="target" position={Position.Left} class="handle-input" />

	<div class="flex flex-col items-center gap-1 p-2">
		<span class="text-xs capitalize">{inputKey}</span>
		<Checkbox
			checked={Boolean(block.inputs.in.value)}
			onCheckedChange={onCheckedChange}
		/>
		<span class="text-xs capitalize">{outputKey}</span>
	</div>

	<Handle id={outputKey} type="source" position={Position.Right} class="handle-output" />
</BlockCommons>

<style>
	:global(.handle-input) {
		background: #93c5fd !important;
	}
	:global(.handle-output) {
		background: #86efac !important;
	}
</style>

// web/src/components/blocks/CheckboxBlock.vue
<script setup lang="ts">
import Checkbox from 'primevue/checkbox';
import { Handle, Position, } from '@vue-flow/core';
import { capitalize } from 'vue';
import { Block } from '../../lib/Block';
import { useEngine } from '../../lib/Engine';
import BlockCommons from '../BlockCommons.vue';

const props = defineProps<{ data: Block }>()
const { command } = useEngine()

function onInputChange(data: boolean) {
	command.writeBlockOutput(props.data.id, Object.keys(props.data.outputs)[0] ?? '', data)
}

</script>

<template>
	<BlockCommons :data="data">
		<template #body>
			<Handle :id="Object.keys(data.inputs)[0] ?? 'in'" type="target" :position="Position.Left"
				class="handle-input" />

			<div class="flex align-items-center justify-content-center m-1 border-round">
				{{ capitalize(Object.keys(data.inputs)[0] ?? '') }}
			</div>

			<div class="flex align-items-center justify-content-center m-1 border-round">
				<Checkbox v-model="data.inputs.in.value" :binary="true" v-on:update:model-value="onInputChange" />
			</div>

			<div class="flex align-items-center justify-content-center m-1 border-round">
				{{ capitalize(Object.keys(data.outputs)[0] ?? '') }}
			</div>

			<Handle :id="Object.keys(data.outputs)[0] ?? 'out'" type="source" :position="Position.Right"
				class="handle-output" />
		</template>
	</BlockCommons>
</template>

<style scoped>
@import '../../assets/js-block.css';

.handle-input {
	background: var(--blue-200);
}

.handle-output {
	background: var(--green-200);
}
</style>
