// web/src/components/blocks/InputBlock.vue
<script setup lang="ts">
import { Handle, Position, } from '@vue-flow/core';
import InputTex from 'primevue/inputtext';
import { capitalize, onMounted } from 'vue';
import { Block } from '../../lib/Block';
import { useEngine } from '../../lib/Engine';
import BlockCommons from '../BlockCommons.vue';

const props = defineProps<{ data: Block }>()
const { command } = useEngine()

onMounted(() => {
	if (props.data.inputs.in.value == null && props.data.outputs.out.value != null) {
		props.data.inputs.in.value = props.data.outputs.out.value
	}
})

function onInputChange(data: string) {
	props.data.outputs.out.value = data
	command.writeBlockOutput(props.data.id, Object.keys(props.data.outputs)[0] ?? '', data)
}

</script>

<template>
	<BlockCommons :data="data">
		<template #body>
			<Handle :id="Object.keys(data.inputs)[0] ?? 'in'" type="target" :position="Position.Left"
				class="handle-input" />

			<div class="flex align-items-center justify-content-center m-1 border-round">
				{{ capitalize(Object.keys(data.inputs)[0] ?? '') }}
			</div>

			<div class="flex align-items-center justify-content-center m-1 border-round">
				<InputTex :value="data.inputs.in.value" v-on:update:model-value="onInputChange" size="small" />
			</div>

			<div class="flex align-items-center justify-content-center m-1 border-round">
				{{ capitalize(Object.keys(data.outputs)[0] ?? '') }}
			</div>

			<Handle :id="Object.keys(data.outputs)[0] ?? 'out'" type="source" :position="Position.Right"
				class="handle-output" />
		</template>
	</BlockCommons>
</template>

<style scoped>
@import '../../assets/js-block.css';

.handle-input {
	background: var(--blue-200);
}

.handle-output {
	background: var(--green-200);
}
</style>

// web/src/components/blocks/InputBlock.svelte
<script lang="ts">
	import { Handle, Position } from '@xyflow/svelte';
	import { onMount } from 'svelte';
	import { Input } from '$lib/components/ui/input';
	import BlockCommons from '../BlockCommons.svelte';
	import { useEngine } from '$lib/Engine';
	import type { Block } from '$lib/Block';

	interface Props {
		data: { value: Block };
	}

	let { data }: Props = $props();
	const { command } = useEngine();

	const block = $derived(data.value);
	const inputKey = $derived(Object.keys(block.inputs)[0] ?? 'in');
	const outputKey = $derived(Object.keys(block.outputs)[0] ?? 'out');

	onMount(() => {
		if (block.inputs.in.value == null && block.outputs.out.value != null) {
			block.inputs.in.value = block.outputs.out.value;
		}
	});

	function onInputChange(event: Event) {
		const val = (event.target as HTMLInputElement).value;
		block.outputs.out.value = val;
		command.writeBlockOutput(block.id, outputKey, val);
	}
</script>

<BlockCommons data={block}>
	<Handle id={inputKey} type="target" position={Position.Left} class="handle-input" />

	<div class="flex flex-col items-center gap-1 p-1">
		<span class="text-xs capitalize">{inputKey}</span>
		<Input
			value={String(block.inputs.in.value ?? '')}
			oninput={onInputChange}
			class="h-7 w-24 text-xs"
		/>
		<span class="text-xs capitalize">{outputKey}</span>
	</div>

	<Handle id={outputKey} type="source" position={Position.Right} class="handle-output" />
</BlockCommons>

<style>
	:global(.handle-input) {
		background: #93c5fd !important;
	}
	:global(.handle-output) {
		background: #86efac !important;
	}
</style>
