// web/src/components/blocks/CheckboxBlock.vue
<script setup lang="ts">
import Checkbox from 'primevue/checkbox';
import { Handle, Position, } from '@vue-flow/core';
import { capitalize } from 'vue';

import { command } from '../../lib/Engine';
import { Block } from '../../lib/Block';

const props = defineProps<{ data: Block }>()

function onInputChange(data: string) {
	command.writeBlockOutput(props.data.id, Object.keys(props.data.outputs)[0] ?? '', data)
}

</script>

<template>
	<div class="flex">
		<Handle :id="Object.keys(data.inputs)[0] ?? 'in'" type="target" :position="Position.Left" class="handle-input" />

		<div class="flex align-items-center justify-content-center m-1 border-round">
			{{ capitalize(Object.keys(data.inputs)[0] ?? '') }}
		</div>

		<div class="flex align-items-center justify-content-center m-1 border-round">
			<Checkbox :value="data.inputs.in.value" v-on:update:model-value="onInputChange" />
		</div>

		<div class="flex align-items-center justify-content-center m-1 border-round">
			{{ capitalize(Object.keys(data.outputs)[0] ?? '') }}
		</div>

		<Handle :id="Object.keys(data.outputs)[0] ?? 'out'" type="source" :position="Position.Right"
			class="handle-output" />
	</div>
</template>

<style scoped>
[class*="handle-"] {
	padding: 1px;
	display: inline-table;
	height: 1em;
	border-radius: 10%;
	overflow: hidden;
}

.handle-input {
	background: var(--blue-200);
}

.handle-output {
	background: var(--green-200);
}
</style>

// web/app/src/components/blocks/CheckboxBlock.svelte
<script lang="ts">
	import { Handle, Position } from '@xyflow/svelte';
	import { Checkbox } from '$lib/components/ui/checkbox';
	import BlockCommons from '../BlockCommons.svelte';
	import { useEngine } from '$lib/Engine';
	import type { Block } from '$lib/Block';

	interface Props {
		data: { value: Block };
	}

	let { data }: Props = $props();
	const { command } = useEngine();

	const block = $derived(data.value);
	const inputKey = $derived(Object.keys(block.inputs)[0] ?? 'in');
	const outputKey = $derived(Object.keys(block.outputs)[0] ?? 'out');

	function onCheckedChange(checked: boolean) {
		command.writeBlockOutput(block.id, outputKey, checked);
	}
</script>

<BlockCommons data={block}>
	<div class="ui-block-body">
		<Handle id={inputKey} type="target" position={Position.Left} class="handle-dot handle-input" />
		<Checkbox
			checked={Boolean(block.inputs.in.value)}
			onCheckedChange={onCheckedChange}
		/>
		<Handle id={outputKey} type="source" position={Position.Right} class="handle-dot handle-output" />
	</div>
</BlockCommons>

<style>
	.ui-block-body {
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 6px 10px;
		position: relative;
	}

	:global(.handle-dot) {
		width: 8px !important;
		height: 8px !important;
		border-radius: 50% !important;
		min-width: 0 !important;
		border: 1.5px solid white !important;
	}
	:global(.handle-input) { background: #6b9eff !important; }
	:global(.handle-output) { background: #6bcf7f !important; }
</style>
