// web/src/components/BlockNode.svelte
<script lang="ts">
	import type { Block } from '$lib/Block';
	import GenericBlock from './blocks/GenericBlock.svelte';
	import InputBlock from './blocks/InputBlock.svelte';
	import CheckboxBlock from './blocks/CheckboxBlock.svelte';
	import ChartBlock from './blocks/ChartBlock.svelte';
	import GaugeBlock from './blocks/GaugeBlock.svelte';

	interface Props {
		data: { value: Block };
	}

	let { data }: Props = $props();

	const block = $derived(data.value);
</script>

{#if block.desc.implementation === 'native'}
	<GenericBlock {data} />
{:else if block.desc.name === 'Input'}
	<InputBlock {data} />
{:else if block.desc.name === 'Checkbox'}
	<CheckboxBlock {data} />
{:else if block.desc.name === 'Chart'}
	<ChartBlock {data} />
{:else if block.desc.name === 'Gauge'}
	<GaugeBlock {data} />
{:else}
	<GenericBlock {data} />
{/if}

// web/src/components/BlockNode.vue
<script setup lang="ts">
import { Block } from '../lib/Block';
import BlockNode from './blocks/GenericBlock.vue';
import ChartBlock from './blocks/ChartBlock.vue';
import CheckboxBlock from './blocks/CheckboxBlock.vue';
import InputBlock from './blocks/InputBlock.vue';
import GaugeBlock from './blocks/GaugeBlock.vue';

defineProps<{ data: Block }>()

</script>

<template>
	<BlockNode v-if="data.desc.implementation == 'native'" :data="data" />
	<InputBlock v-else-if="data.desc.implementation == 'external' && data.desc.name == 'Input'" :data="data" />
	<CheckboxBlock v-else-if="data.desc.implementation == 'external' && data.desc.name == 'Checkbox'" :data="data" />
	<ChartBlock v-else-if="data.desc.implementation == 'external' && data.desc.name == 'Chart'" :data="data" />
	<GaugeBlock v-else-if="data.desc.implementation == 'external' && data.desc.name == 'Gauge'" :data="data" />
	<BlockNode v-else :data="data" />
</template>
